#!/bin/bash

# this script takes the output of the 'openbox-menu' command 
# and strips it to display only applications of the category that
# is passed to the script ($1)
# this data is then piped into the openbox menu.

echo '<openbox_pipe_menu xmlns="http://openbox.org/"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://openbox.org/  file:///usr/share/openbox/menu.xsd">'

dyn_output=`/usr/bin/openbox-menu -i lxde-applications.menu|sed -e "/openbox-$1/,/\/menu/!d"|grep -v "openbox-$1"|grep -v '/menu'`
if [[ "$dyn_output" == "" ]]; then
  echo '<item label="(empty)"></item>'
else
  echo "$dyn_output"  
fi

echo '</openbox_pipe_menu>'
