#!/bin/bash
# Openbox wallpaper changer using feh
#  

function feh_pipe()
{
for f in ${1}/*.{jpg,png}
do
	echo "<item label=\"$(basename ${f%.*})\">
	<action name=\"Execute\">
	<command>feh --bg-scale \"$f\"</command>
	</action>
	</item>"
done
}

echo "<openbox_pipe_menu>"
# Simply change paths to suit
feh_pipe /home/guest/.wallpaper
feh_pipe /usr/share/wallpapers
feh_pipe /usr/share/backgrounds/xfce
echo "</openbox_pipe_menu>"